"use client";
import React, { useState } from "react";
import Box from "@mui/material/Box";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import Pagination from "@mui/material/Pagination";
import TableRow from "@mui/material/TableRow";
import TableSortLabel from "@mui/material/TableSortLabel";
import Paper from "@mui/material/Paper";
import { visuallyHidden } from "@mui/utils";
import useMaterialTableHook from "@/hooks/useMaterialTableHook";
import { Checkbox } from "@mui/material";
import TableControls from "@/components/elements/SharedInputs/TableControls";
import DeleteModal from "@/components/common/DeleteModal";
import ReportDetailsModal from "./ReportDetailsModal";
import { getTableStatusClass } from "@/hooks/use-condition-class";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import DescriptionIcon from "@mui/icons-material/Description";
import DownloadIcon from "@mui/icons-material/Download";

// Define Report interface
interface IHrReport {
  id: number;
  reportName: string;
  reportType: string;
  generatedBy: string;
  generationDate: string;
  period: string;
  status: string;
  fileSize: string;
  recordCount: number;
  downloadCount: number;
  [key: string]: any;
}

// Mock data
const hrReportsData: IHrReport[] = [
  {
    id: 1,
    reportName: "Monthly Attendance Summary",
    reportType: "Attendance",
    generatedBy: "John Doe",
    generationDate: "2024-03-31",
    period: "March 2024",
    status: "Complete",
    fileSize: "2.5 MB",
    recordCount: 250,
    downloadCount: 15
  },
  {
    id: 2,
    reportName: "Employee Turnover Analysis",
    reportType: "Analytics",
    generatedBy: "Jane Smith",
    generationDate: "2024-03-28",
    period: "Q1 2024",
    status: "Complete",
    fileSize: "1.8 MB",
    recordCount: 120,
    downloadCount: 8
  },
  {
    id: 3,
    reportName: "Leave Balance Report",
    reportType: "Leave",
    generatedBy: "Mike Johnson",
    generationDate: "2024-03-25",
    period: "March 2024",
    status: "Pending",
    fileSize: "1.2 MB",
    recordCount: 85,
    downloadCount: 3
  },
  {
    id: 4,
    reportName: "Payroll Summary",
    reportType: "Payroll",
    generatedBy: "Sarah Wilson",
    generationDate: "2024-03-20",
    period: "March 2024",
    status: "Complete",
    fileSize: "3.5 MB",
    recordCount: 300,
    downloadCount: 22
  },
  {
    id: 5,
    reportName: "Training Completion Report",
    reportType: "Training",
    generatedBy: "Robert Brown",
    generationDate: "2024-03-18",
    period: "Q1 2024",
    status: "Complete",
    fileSize: "2.1 MB",
    recordCount: 180,
    downloadCount: 12
  },
  {
    id: 6,
    reportName: "Performance Review Summary",
    reportType: "Performance",
    generatedBy: "Emily Davis",
    generationDate: "2024-03-15",
    period: "Q4 2023",
    status: "Failed",
    fileSize: "N/A",
    recordCount: 0,
    downloadCount: 0
  },
  {
    id: 7,
    reportName: "Recruitment Metrics",
    reportType: "Recruitment",
    generatedBy: "David Miller",
    generationDate: "2024-03-10",
    period: "Q1 2024",
    status: "Complete",
    fileSize: "1.5 MB",
    recordCount: 95,
    downloadCount: 7
  },
  {
    id: 8,
    reportName: "Employee Demographics",
    reportType: "Analytics",
    generatedBy: "Lisa Taylor",
    generationDate: "2024-03-05",
    period: "March 2024",
    status: "In Progress",
    fileSize: "2.8 MB",
    recordCount: 210,
    downloadCount: 5
  },
  {
    id: 9,
    reportName: "Compliance Audit Report",
    reportType: "Compliance",
    generatedBy: "James Anderson",
    generationDate: "2024-02-28",
    period: "February 2024",
    status: "Complete",
    fileSize: "4.2 MB",
    recordCount: 400,
    downloadCount: 18
  },
  {
    id: 10,
    reportName: "Benefits Enrollment Summary",
    reportType: "Benefits",
    generatedBy: "Amanda Thomas",
    generationDate: "2024-02-25",
    period: "February 2024",
    status: "Complete",
    fileSize: "1.9 MB",
    recordCount: 150,
    downloadCount: 9
  }
];

// Table head cells
const hrReportHeadCells = [
  { id: "reportName", label: "Report Name" },
  { id: "reportType", label: "Type" },
  { id: "generatedBy", label: "Generated By" },
  { id: "generationDate", label: "Date" },
  { id: "period", label: "Period" },
  { id: "status", label: "Status" },
  { id: "fileSize", label: "File Size" },
  { id: "recordCount", label: "Records" },
  { id: "downloadCount", label: "Downloads" },
];

interface HrReportsTableProps {
  reportType?: string;
  dateRange?: { start: string; end: string };
}

const HrReportsTable: React.FC<HrReportsTableProps> = ({ 
  reportType = "all",
  dateRange 
}) => {
  const [modalOpen, setModalOpen] = useState(false);
  const [detailsModalOpen, setDetailsModalOpen] = useState(false);
  const [editData, setEditData] = useState<IHrReport | null>(null);
  const [modalDeleteOpen, setModalDeleteOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<number>(0);
  
  // Filter data based on report type and date range
  const filteredData = hrReportsData.filter(report => {
    // Filter by report type
    if (reportType !== "all" && report.reportType !== reportType) {
      return false;
    }
    
    // Filter by date range if provided
    if (dateRange) {
      const reportDate = new Date(report.generationDate);
      const startDate = new Date(dateRange.start);
      const endDate = new Date(dateRange.end);
      return reportDate >= startDate && reportDate <= endDate;
    }
    
    return true;
  });
  
  const {
    order,
    orderBy,
    selected,
    page,
    rowsPerPage,
    searchQuery,
    paginatedRows,
    filteredRows,
    handleDelete,
    handleRequestSort,
    handleSelectAllClick,
    handleClick,
    handleChangePage,
    handleChangeRowsPerPage,
    handleSearchChange,
  } = useMaterialTableHook<IHrReport>(filteredData, 10);

  // Helper function for report type badge
  const getReportTypeClass = (type: string) => {
    switch (type.toLowerCase()) {
      case "attendance":
        return "bg-info";
      case "payroll":
        return "bg-success";
      case "leave":
        return "bg-warning";
      case "performance":
        return "bg-danger";
      case "recruitment":
        return "bg-primary";
      case "training":
        return "bg-secondary";
      case "analytics":
        return "bg-dark";
      case "compliance":
        return "bg-info";
      case "benefits":
        return "bg-success";
      default:
        return "default-badge";
    }
  };

  const handleDownloadReport = (report: IHrReport) => {
    // Simulate download
    console.log(`Downloading report: ${report.reportName}`);
    alert(`Downloading ${report.reportName}...`);
  };

  const handleViewReport = (report: IHrReport) => {
    setEditData(report);
    setDetailsModalOpen(true);
  };

  return (
    <>
      <div className="col-span-12">
        <div className="card__wrapper">
          <div className="manaz-common-mat-list w-full table__wrapper table-responsive">
            <TableControls
              rowsPerPage={rowsPerPage}
              searchQuery={searchQuery}
              handleChangeRowsPerPage={handleChangeRowsPerPage}
              handleSearchChange={handleSearchChange}
            />
            
            <Box sx={{ width: "100%" }} className="table-responsive">
              <Paper sx={{ width: "100%", mb: 2 }}>
                <TableContainer className="table mb-[20px] hover multiple_tables w-full">
                  <Table aria-labelledby="tableTitle" className="whitespace-nowrap">
                    <TableHead>
                      <TableRow className="table__title">
                        <TableCell padding="checkbox">
                          <Checkbox
                            className="custom-checkbox checkbox-small"
                            color="primary"
                            indeterminate={selected.length > 0 && selected.length < filteredRows.length}
                            checked={filteredRows.length > 0 && selected.length === filteredRows.length}
                            onChange={(e) => handleSelectAllClick(e.target.checked, filteredRows)}
                            size="small"
                          />
                        </TableCell>
                        {hrReportHeadCells.map((headCell) => (
                          <TableCell
                            className="table__title"
                            key={headCell.id}
                            sortDirection={orderBy === headCell.id ? order : false}
                          >
                            <TableSortLabel
                              active={orderBy === headCell.id}
                              direction={orderBy === headCell.id ? order : "asc"}
                              onClick={() => handleRequestSort(headCell.id)}
                            >
                              {headCell.label}
                              {orderBy === headCell.id ? (
                                <Box component="span" sx={visuallyHidden}>
                                  {order === "desc" ? "sorted descending" : "sorted ascending"}
                                </Box>
                              ) : null}
                            </TableSortLabel>
                          </TableCell>
                        ))}
                        <TableCell>Actions</TableCell>
                      </TableRow>
                    </TableHead>
                    
                    <TableBody className="table__body">
                      {paginatedRows.map((row, index) => {
                        const statusClass = getTableStatusClass(row.status);
                        const typeClass = getReportTypeClass(row.reportType);
                        
                        return (
                          <TableRow
                            key={row.id}
                            selected={selected.includes(index)}
                            onClick={() => handleClick(index)}
                          >
                            <TableCell padding="checkbox">
                              <Checkbox
                                className="custom-checkbox checkbox-small"
                                checked={selected.includes(index)}
                                size="small"
                                onChange={() => handleClick(index)}
                              />
                            </TableCell>
                            <TableCell>
                              <div className="flex items-center">
                                <DescriptionIcon className="mr-2 text-gray-500" fontSize="small" />
                                {row.reportName}
                              </div>
                            </TableCell>
                            <TableCell>
                              <span className={`bd-badge ${typeClass}`}>
                                {row.reportType}
                              </span>
                            </TableCell>
                            <TableCell>{row.generatedBy}</TableCell>
                            <TableCell>{row.generationDate}</TableCell>
                            <TableCell>{row.period}</TableCell>
                            <TableCell>
                              <span className={`bd-badge ${statusClass}`}>
                                {row.status}
                              </span>
                            </TableCell>
                            <TableCell>
                              <span className="font-medium">{row.fileSize}</span>
                            </TableCell>
                            <TableCell>
                              <span className="font-semibold">{row.recordCount}</span>
                            </TableCell>
                            <TableCell>
                              <span className="font-semibold">{row.downloadCount}</span>
                            </TableCell>
                            <TableCell className="table__icon-box">
                              <div className="flex items-center justify-start gap-[10px]">
                                <button
                                  type="button"
                                  className="table__icon download"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleViewReport(row);
                                  }}
                                  title="View Report"
                                >
                                  <i className="fa-regular fa-eye"></i>
                                </button>
                                <button
                                  type="button"
                                  className="table__icon edit"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleDownloadReport(row);
                                  }}
                                  title="Download Report"
                                >
                                  <i className="fa-sharp fa-light fa-download"></i>
                                </button>
                                <button
                                  className="removeBtn table__icon delete"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    setDeleteId(row.id);
                                    setModalDeleteOpen(true);
                                  }}
                                  title="Delete Report"
                                >
                                  <i className="fa-regular fa-trash"></i>
                                </button>
                                {row.status === "Complete" && (
                                  <button
                                    type="button"
                                    className="table__icon bg-cyan-500/50"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleDownloadReport(row);
                                    }}
                                    title="Download PDF"
                                  >
                                    <PictureAsPdfIcon fontSize="small" />
                                  </button>
                                )}
                              </div>
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </TableContainer>
              </Paper>
            </Box>
            
            <Box className="table-search-box mt-[30px]" sx={{ p: 2 }}>
              <Box>
                {`Showing ${(page - 1) * rowsPerPage + 1} to ${Math.min(
                  page * rowsPerPage,
                  filteredRows.length
                )} of ${filteredRows.length} entries`}
                {reportType !== "all" && (
                  <span className="ml-2 text-sm text-gray-600">
                    (Filtered by: {reportType})
                  </span>
                )}
              </Box>
              <Pagination
                count={Math.ceil(filteredRows.length / rowsPerPage)}
                page={page}
                onChange={(e, value) => handleChangePage(value)}
                variant="outlined"
                shape="rounded"
                className="manaz-pagination-button"
              />
            </Box>
          </div>
        </div>
      </div>

      {detailsModalOpen && editData && (
        <ReportDetailsModal
          open={detailsModalOpen}
          setOpen={setDetailsModalOpen}
          reportData={editData}
        />
      )}

      {modalDeleteOpen && (
       <DeleteModal
  open={modalDeleteOpen}
  setOpen={setModalDeleteOpen}
  onConfirm={() => handleDelete(deleteId)}
/>

      )}
    </>
  );
};

export default HrReportsTable;