"use client";
import React from "react";
import { 
  Dialog, 
  DialogTitle, 
  DialogContent, 
  Typography, 
  Chip, 
  Box, 
  Divider, 
  Grid,
  Button
} from "@mui/material";
import { reportDetailsStatePropsType } from "./hreports.interface"
import { getTableStatusClass } from "@/hooks/use-condition-class";
import DescriptionIcon from "@mui/icons-material/Description";
import PersonIcon from "@mui/icons-material/Person";
import CalendarTodayIcon from "@mui/icons-material/CalendarToday";
import InsertDriveFileIcon from "@mui/icons-material/InsertDriveFile";
import BarChartIcon from "@mui/icons-material/BarChart";
import DownloadIcon from "@mui/icons-material/Download";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import ShareIcon from "@mui/icons-material/Share";

interface IHrReport {
  id: number;
  reportName: string;
  reportType: string;
  generatedBy: string;
  generationDate: string;
  period: string;
  status: string;
  fileSize: string;
  recordCount: number;
  downloadCount: number;
  description?: string;
  parameters?: Record<string, any>;
}

const ReportDetailsModal = ({ 
  open, 
  setOpen, 
  reportData 
}: reportDetailsStatePropsType & { reportData: IHrReport | null }) => {
  
  const handleToggle = () => setOpen(!open);

  if (!reportData) return null;

  const getReportTypeClass = (type: string) => {
    switch (type.toLowerCase()) {
      case "attendance":
        return "info-badge";
      case "payroll":
        return "success-badge";
      case "leave":
        return "warning-badge";
      case "performance":
        return "danger-badge";
      case "recruitment":
        return "primary-badge";
      default:
        return "default-badge";
    }
  };

  const handleDownload = () => {
    alert(`Downloading ${reportData.reportName}...`);
  };

  const handleShare = () => {
    alert(`Sharing ${reportData.reportName}...`);
  };

  return (
    <Dialog open={open} onClose={handleToggle} fullWidth maxWidth="md">
      <DialogTitle>
        <div className="flex justify-between items-center">
          <h5 className="modal-title">Report Details</h5>
          <button onClick={handleToggle} type="button" className="bd-btn-close">
            <i className="fa-solid fa-xmark-large"></i>
          </button>
        </div>
      </DialogTitle>
      
      <DialogContent className="common-scrollbar overflow-y-auto">
        <div className="card__wrapper">
          <div className="grid grid-cols-12 gap-y-5">
            <div className="col-span-12">
              <div className="flex justify-between items-start mb-4">
                <div className="flex items-center">
                  <DescriptionIcon className="mr-3 text-primary" fontSize="large" />
                  <div>
                    <Typography variant="h6" className="font-semibold">
                      {reportData.reportName}
                    </Typography>
                    <div className="flex items-center gap-2 mt-1">
                      <Chip 
                        label={reportData.reportType} 
                        className={getReportTypeClass(reportData.reportType)}
                        size="small"
                      />
                      <Chip 
                        label={reportData.status} 
                        className={getTableStatusClass(reportData.status)}
                        size="small"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <Divider className="col-span-12 my-2" />
            
            <Grid container spacing={2} className="col-span-12">
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <div className="flex items-center gap-2">
                    <PersonIcon fontSize="small" color="action" />
                    <span className="label__subtitle">Generated By</span>
                  </div>
                  <h6 className="label__title">{reportData.generatedBy}</h6>
                </div>
              </Grid>
              
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <div className="flex items-center gap-2">
                    <CalendarTodayIcon fontSize="small" color="action" />
                    <span className="label__subtitle">Generation Date</span>
                  </div>
                  <h6 className="label__title">{reportData.generationDate}</h6>
                </div>
              </Grid>
              
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <span className="label__subtitle">Report Period</span>
                  <h6 className="label__title">{reportData.period}</h6>
                </div>
              </Grid>
              
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <div className="flex items-center gap-2">
                    <InsertDriveFileIcon fontSize="small" color="action" />
                    <span className="label__subtitle">File Size</span>
                  </div>
                  <h6 className="label__title">{reportData.fileSize}</h6>
                </div>
              </Grid>
              
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <div className="flex items-center gap-2">
                    <BarChartIcon fontSize="small" color="action" />
                    <span className="label__subtitle">Record Count</span>
                  </div>
                  <h6 className="label__title">{reportData.recordCount.toLocaleString()} records</h6>
                </div>
              </Grid>
              
              <Grid item xs={12} md={6}>
                <div className="label__content-wrapper">
                  <span className="label__subtitle">Download Count</span>
                  <h6 className="label__title">{reportData.downloadCount} downloads</h6>
                </div>
              </Grid>
            </Grid>
            
            <Divider className="col-span-12 my-2" />
            
            <div className="col-span-12">
              <Typography variant="subtitle1" className="font-medium mb-3">
                Report Description
              </Typography>
              <Box className="p-3 bg-gray-50 rounded-lg">
                <Typography variant="body2">
                  {reportData.description || 
                    `This ${reportData.reportType.toLowerCase()} report provides detailed analysis and insights for the period ${reportData.period}. 
                    It includes comprehensive data and metrics relevant to HR operations and decision-making.`}
                </Typography>
              </Box>
            </div>
            
            {reportData.parameters && Object.keys(reportData.parameters).length > 0 && (
              <>
                <Divider className="col-span-12 my-2" />
                <div className="col-span-12">
                  <Typography variant="subtitle1" className="font-medium mb-3">
                    Report Parameters
                  </Typography>
                  <Box className="p-3 bg-blue-50 rounded-lg">
                    <Grid container spacing={2}>
                      {Object.entries(reportData.parameters).map(([key, value], index) => (
                        <Grid item xs={12} md={6} key={index}>
                          <Typography variant="body2">
                            <strong>{key}:</strong> {String(value)}
                          </Typography>
                        </Grid>
                      ))}
                    </Grid>
                  </Box>
                </div>
              </>
            )}
            
            <Divider className="col-span-12 my-4" />
            
            <div className="col-span-12">
              <div className="flex flex-wrap gap-3 justify-center">
                <Button
                  variant="contained"
                  color="primary"
                  startIcon={<DownloadIcon />}
                  onClick={handleDownload}
                >
                  Download Report
                </Button>
                <Button
                  variant="outlined"
                  color="secondary"
                  startIcon={<PictureAsPdfIcon />}
                  onClick={handleDownload}
                >
                  Download PDF
                </Button>
                <Button
                  variant="outlined"
                  color="info"
                  startIcon={<ShareIcon />}
                  onClick={handleShare}
                >
                  Share Report
                </Button>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ReportDetailsModal;